### ISSUE TITLE
Mismatch of downloaded data (cds, pep, gff)

### ISSUE THREAD

**Issue by Siadjeu** [SunPengChuan/wgdi-example#4]
I'm having trouble obtaining the lens file and gff file using your code (deal_gff_ncbi.py
). I have downloaded the GFF3, PEP and CDS files from the website: http://bioinfo.sibs.ac.cn/Am/download_v2.php
Could you please help me fix this problem? Thank you

**Comment by SunPengChuan** [comment]
Sorry, I can't access this data. Could you please send it to my email: [sunpengchuan@gmail.com](mailto:sunpengchuan@gmail.com)?
