### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Siadjeu** [SunPengChuan/wgdi-example#5]
Dear Pengchuan, Sorry to bother you again! I was running the code until I wanted to generate the KsFigure. I got this error message. I tried to follow your suggestion from this post (https://github.com/SunPengChuan/wgdi/issues/3), but I couldn't fix the issue. Could you please have a look? Here's my code.

ksfit  =  amas1_vpanor_ksmedain.csv
labelfontsize  =  15
legendfontsize  =  15
xlabel  =  none
ylabel  =  none
title  =  none
area  =  0,4
figsize  =  10,6.18
shadow  =  true (true/false)
savefig  =  amas1_vpanorKSfigure.png

**Comment by SunPengChuan** [comment]
Does the file "amas1_vpanor_ksmedain.csv" have any content? Can you provide it?

**Comment by Siadjeu** [comment]
I just sent you the file! Thank you!

**Comment by SunPengChuan** [comment]
The file "amas1_vpanor_ksmedain.csv" is incorrect. Here, "ksfit" refers to another file. Use the command to enter the folder: wgdi -kf ? >> total.conf. Extract the parameter file for "kffit" (which is "ks_fit_result.csv"). The file parameters need to be modified, and the results come from the "-pf" parameter.

**Comment by Siadjeu** [comment]
Thank you! It works now!

Best wishes,

Christian

Le mar. 30 juil. 2024 à 15:57, sunpengchuan ***@***.***> a
écrit :
